### ISSUE TITLE
Call controls not displayed after publishing CALL_STARTED event

### ISSUE THREAD

**Issue by nickl-1000** [salesforce/scv-connector-base#14]
I'm on a GS0 org and this issue started today - it was working on Feb 25.

When I publish a CALL_STARTED event for an incoming call the Phone controls are blank:
![image](https://user-images.githubusercontent.com/100615905/156037975-df72bd78-81ed-4e10-b2a8-11ee3603f4d9.png)

If I answer the call (I have to do this from another instance of the phone) I do get controls but it doesn't display the voice call record.

Here is what I'm sending in the CALL_STARTED event:
`{
  "eventType": "CALL_STARTED",
  "payload": {
    "call": {
      "callId": "947beb60-4f07-4108-ae95-6a57396e10b1",
      "callType": "Inbound",
      "phoneNumber": "1012",
      "callInfo": {
        "callStateTimestamp": "2022-02-28T18:28:23.209Z",
        "isRecordingPaused": true,
        "isMuted": false,
        "isOnHold": false,
        "isSoftphoneCall": true,
        "acceptEnabled": true,
        "declineEnabled": true,
        "muteEnabled": true,
        "swapEnabled": true,
        "conferenceEnabled": true,
        "holdEnabled": true,
        "recordEnabled": true,
        "addCallerEnabled": true,
        "extensionEnabled": true,
        "isReplayable": true,
        "removeParticipantVariant": "ALWAYS"
      },
      "contact": {
        "phoneNumber": "1012",
        "name": "",
        "prefix": "",
        "extension": "",
        "availability": null
      },
      "state": "ringing",
      "callAttributes": {
        "voiceCallId": "0LQB0000002Axe8",
        "participantType": "Initial_Caller",
        "parentId": "",
        "isOnHold": false,
        "dialerType": "None"
      },
      "totalHoldDuration": 0,
      "longestHoldDuration": 0,
      "numberOfHolds": 0,
      "startTime": 1646072903209,
      "vendorCallKey": "51d301ba-c61a-4616-914b-25f422a4e2b4"
    }
  },
  "registerLog": false
}`

**Comment by estrudels** [comment]
I am also encountering the issue that @nickl-1000 has described

**Comment by aizazhakro** [comment]
We had an issue with our GS0 instance which has now been resolved. Can you please try again in your org and let us know if  it's fixed for you?

**Comment by estrudels** [comment]
@aizazhakro 
- I am now UNABLE to reproduce the issue after the recent changes. 👍🏼
- Everything is running as expected now.
- Thanks for the quick feedback & update. 

![All-Good](https://user-images.githubusercontent.com/100722689/156249329-f2ef6f60-7c72-406f-b16a-ad759bff950e.png)

**Comment by nickl-1000** [comment]
This is working for me now, thanks.
