### ISSUE TITLE
publishEvent for HANGUP should return HangupResult not CallResult

### ISSUE THREAD

**Issue by Prochniak** [salesforce/scv-connector-base#21]
Incorrect information in docs for publishEvent, for hangup event in payload we should have HangupResult, but in documentation is CallResult https://developer.salesforce.com/docs/atlas.en-us.236.0.voice_pt_developer_guide.meta/voice_pt_developer_guide/voice_pt_connector_base_publishevent.htm

**Comment by sfyz** [comment]
Thanks for the note. I'll update the documentation so it goes out with the next doc release, which I believe will be live in a week.

**Comment by estrudels** [comment]
@sfyz The **doc release** you were talking about happen, or still in-progress? Thanks

**Comment by sfyz** [comment]
@estrudels Oh yes, sorry, it looks like this original URL links to version "236.0" of the document, but if you look at the latest release (240, aka API v56.0, aka Winter '23 😜), then I believe it is accurate: https://developer.salesforce.com/docs/atlas.en-us.voice_pt_developer_guide.meta/voice_pt_developer_guide/voice_pt_connector_base_publishevent.htm

**Comment by estrudels** [comment]
@sfyz  Yes everything seems to be in order and accurate in version `236.0` (API 56.0) documentation! Thank you!

@Prochniak Thank you for closing this ticket as complete 😃
