### ISSUE TITLE
Supervisor Typescript definitions incorrect

### ISSUE THREAD

**Issue by SebOpalinski** [salesforce/scv-connector-base#25]
The Typescript definition for superviseCall is:
`superviseCall(call: PhoneCall): void;` 

However, the actual function definition should look like this:
`superviseCall (supervisedCallInfo: SupervisedCallInfo): Promise<SuperviseCallResult>`

**Comment by estrudels** [comment]
@SebOpalinski  Yes we have also found this to be an issue

When will there be an update to scv-connector-base to have the proper typings?

[dlouvton](https://github.com/dlouvton) [sfyz](https://github.com/sfyz)

**Comment by krishnan-force** [comment]
@estrudels yes working on it. Will update shortly

**Comment by krishnan-force** [comment]
should be fixed. we will publish a new package 3.5.2 soon
