### ISSUE TITLE
ts-declaration for addParticipant method incorrect 

### ISSUE THREAD

**Issue by ssdey1** [salesforce/scv-connector-base#27]
The current ts-declaration for addParticipant method is:
addParticipant(contact: Contact, call: PhoneCall): Promise<ParticipantResult>

The actual  ts-declaration should look like this:
addParticipant(contact: Contact, call: PhoneCall, isBlindTransfer: Boolean): Promise<ParticipantResult>

**Comment by estrudels** [comment]
Yes we have also found this to be an issue

When will there be an update to **scv-connector-base** to have the proper typings?

**Comment by vivektikoo-force** [comment]
This issue is fixed in https://github.com/salesforce/scv-connector-base/pull/30. We will publish a new version soon
