### ISSUE TITLE
Incorrect Return Type for superviseCall in type.d.ts 

### ISSUE THREAD

**Issue by estrudels** [salesforce/scv-connector-base#42]
Hey Salesforce Team,

I am viewing the following file
-  `scv-connector-base/ts-declaration/types.d.ts`

I noticed the superviseCall return type is incorrect (~ Line 845)

Currently it is

`superviseCall(supervisedCallInfo: SupervisedCallInfo): void;`

It should be (Return a Promise of SuperviseCallResult & not be void)

`superviseCall(supervisedCallInfo: SupervisedCallInfo): Promise<SuperviseCallResult>;`

If you look within
-  `scv-connector-base/src/main/baseConnector.js` (~Line 626 - 627)

In the handler of `constants.MESSAGE_TYPE.SUPERVISE_CALL` you can see that it awaiting the promise and validates the results as a SuperviseCallResult

` const result = await vendorConnector.superviseCall(message.data.call);`
` Validator.validateClassObject(result, SuperviseCallResult);`

Would it be possible to apply a fix for next patch/release?

@krishnan-force @dlouvton @vivektikoo-force @rjanamanchi-sfdc

**Comment by estrudels** [comment]
@krishnan-force @dlouvton @vivektikoo-force  @rjanamanchi-sfdc @fernomac Any comment/clarifciation/advice on this?

**Comment by rjanamanchi-sfdc** [comment]
@estrudels Thanks for reporting this and sorry we didn't reply earlier. We will fix this in the next patch
