### ISSUE TITLE
@salesforce/scv-connector-base or scv-connector-base

### ISSUE THREAD

**Issue by estrudels** [salesforce/scv-connector-base#47]
Could you please confirm which `npm` package we should be using for our integration of Service Cloud Voice.

1. `@salesforce/scv-connector-base` - https://www.npmjs.com/package/@salesforce/scv-connector-base
* We have been using this one historically for the past `3+ Years`

or

2. `scv-connector-base` - https://www.npmjs.com/package/scv-connector-base
* Has been added recently past couple of weeks

Thank you

CC @rjanamanchi-sfdc @dlouvton @vivektikoo-force @rjanamanchi-sfdc @fernomac

**Comment by dlouvton** [comment]
Use
@salesforce/scv-connector-base

**Comment by estrudels** [comment]
Thank you
