### ISSUE TITLE
`getPhoneContacts` method signature doesn't include a parameter for filter options

### ISSUE THREAD

**Issue by mocarz** [salesforce/scv-connector-base#7]
The method signature is:
`getPhoneContacts(): Promise<PhoneContactsResult>`

However `baseConnector.js` sends an argument containing filter options to `getPhoneContacts` method.

The expectation is to add an argument with a proper type for the filter options.

I'm using `scv-connector-base` version `70b82e0e9eb3c925c3ccf6f53cc98f1ed0c2b6eb`.

**Comment by dlouvton** [comment]
The filter is being sent from Salesforce when you use the latest release Summer 21' and if you do a contact search after clicking "add caller". For example,  

![image](https://user-images.githubusercontent.com/6644746/133283119-44f29aa9-d4ae-4fd2-b55b-8d576d0d8219.png)

![image](https://user-images.githubusercontent.com/6644746/133283556-380040c0-9b3b-40af-bd32-e8806cf4c487.png)
