### ISSUE TITLE
Call Duration not updated

### ISSUE THREAD

**Issue by severingafner** [salesforce/scv-connector-base#9]
We found out, that the call duration on voicecalls is not updated.
We send the updateVoiceCall request and all other voicecall fields are updated (e.g. state completed).
We can reproduce it with the demo connector, as well as with our own integration.
After further investigation we found out, that we face this issue since the 09.15.2021 on all Winter'22 orgs.
On Summer'21 orgs, the field is fullfilled.
The problem appears with hardphone and softphone mode.

We would appreciate a short feedback whether you can reproduce this issue or not.

**Comment by estrudels** [comment]
@severingafner Would you consider **Closing Your Issue**, as this does not seem to be a problem in **Winter '23 (API v55)**

**Comment by estrudels** [comment]
@vivektikoo-force Could you close this issue as **Not Reproducible** as all seems good in **Winter '23 (API v56)**

**Comment by vivektikoo-force** [comment]
This is working as expected
